# Generated by Django 5.1.5 on 2025-04-09 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('first', models.CharField(max_length=100)),
                ('second', models.CharField(max_length=100)),
                ('third', models.CharField(max_length=100)),
                ('fourth', models.CharField(max_length=100)),
                ('correct_answer', models.CharField(choices=[('FI', 'First Choice'), ('SE', 'Second Choice'), ('TH', 'Third Choice'), ('FO', 'Fourth Choice')], max_length=2)),
                ('test_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='app.testbox')),
            ],
        ),
    ]
